### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by nivle1661** [KumarRobotics/flir_gige#8]
To my understanding, the images are placed in a buffer so there is lag between when the image is taken and when the image is acquired from the buffer (which is when the timestamp is recorded). Is it possible to get the exact time of when the image itself is taken for more accurate data?
Thanks!

**Comment by versatran01** [comment]
The timestamp is recorded right before we call `Grab`. Then the driver will take the next available image in the buffer. So there's definitely some inconsistency between the recorded timestamp and the actual one when the image is acquired. The problem is that the camera is in free running mode, so it is grabbing images at 10hz (for example). On our side, we have a node running at 10hz and keep retrieving images from the buffer. Ideally, this should work the other way around, letting the camera SDK trigger an image callback whenever an image is ready, and then you can subtract the exposure time to get the actual time. But I don't know if the pleora SDK that used here has such capability though.
